"""add otp model

Revision ID: 10f5ba56364e
Revises: 8effd9431fea
Create Date: 2026-04-17 12:48:02.004322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10f5ba56364e'
down_revision: Union[str, Sequence[str], None] = '8effd9431fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_expires_at'), 'otp', ['expires_at'], unique=False)
    op.create_index(op.f('ix_otp_purpose'), 'otp', ['purpose'], unique=False)
    op.create_index(op.f('ix_otp_target'), 'otp', ['target'], unique=False)
    op.create_index('ix_otp_target_purpose_channel', 'otp', ['target', 'purpose', 'channel'], unique=False)
    op.create_index(op.f('ix_otp_user_id'), 'otp', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_user_id'), table_name='otp')
    op.drop_index('ix_otp_target_purpose_channel', table_name='otp')
    op.drop_index(op.f('ix_otp_target'), table_name='otp')
    op.drop_index(op.f('ix_otp_purpose'), table_name='otp')
    op.drop_index(op.f('ix_otp_expires_at'), table_name='otp')
    op.drop_table('otp')
    # ### end Alembic commands ###
