"""add refresh token table

Revision ID: 6ad6f7e97b9c
Revises: fe7b92fbbbd4
Create Date: 2026-04-11 16:49:55.662974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ad6f7e97b9c'
down_revision: Union[str, Sequence[str], None] = 'fe7b92fbbbd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('refresh_token', sa.Column('token', sa.String(), nullable=False))
    op.add_column('refresh_token', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('refresh_token', sa.Column('revoked', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'refresh_token', ['token'])
    op.create_foreign_key(None, 'refresh_token', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_token', type_='foreignkey')
    op.drop_constraint(None, 'refresh_token', type_='unique')
    op.drop_column('refresh_token', 'revoked')
    op.drop_column('refresh_token', 'expires_at')
    op.drop_column('refresh_token', 'token')
    op.drop_column('refresh_token', 'user_id')
    # ### end Alembic commands ###
