"""some bog fix in refresh token model

Revision ID: 7d04a882d022
Revises: 6ad6f7e97b9c
Create Date: 2026-04-13 14:50:48.269351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d04a882d022'
down_revision: Union[str, Sequence[str], None] = '6ad6f7e97b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('token_id', sa.UUID(), nullable=False))
    op.add_column('refresh_token', sa.Column('token_hash', sa.String(), nullable=False))
    op.drop_constraint(op.f('refresh_token_token_key'), 'refresh_token', type_='unique')
    op.create_index(op.f('ix_refresh_token_token_id'), 'refresh_token', ['token_id'], unique=True)
    op.create_unique_constraint(None, 'refresh_token', ['token_hash'])
    op.drop_column('refresh_token', 'id')
    op.drop_column('refresh_token', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('refresh_token', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'refresh_token', type_='unique')
    op.drop_index(op.f('ix_refresh_token_token_id'), table_name='refresh_token')
    op.create_unique_constraint(op.f('refresh_token_token_key'), 'refresh_token', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_column('refresh_token', 'token_hash')
    op.drop_column('refresh_token', 'token_id')
    # ### end Alembic commands ###
