"""some bog fix in refresh token model

Revision ID: 8effd9431fea
Revises: 1db7f7027d59
Create Date: 2026-04-14 13:42:32.244509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8effd9431fea'
down_revision: Union[str, Sequence[str], None] = '1db7f7027d59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_refresh_token_user_id'), 'refresh_token', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_token_user_id'), table_name='refresh_token')
    # ### end Alembic commands ###
