"""fix some things

Revision ID: 90c0d92c189b
Revises: d042f09072c0
Create Date: 2026-04-26 11:09:23.961109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c0d92c189b'
down_revision: Union[str, Sequence[str], None] = 'd042f09072c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_project_id_team_id', 'projects', ['id', 'team_id'])
    op.create_table('project_user',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id', 'team_id'], ['projects.id', 'projects.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id', 'team_id'], ['team_user.user_id', 'team_user.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    op.create_index(op.f('ix_project_user_team_id'), 'project_user', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_user_team_id'), table_name='project_user')
    op.drop_table('project_user')
    op.drop_constraint('uq_project_id_team_id', 'projects', type_='unique')

    # ### end Alembic commands ###
