"""add owner id to role model

Revision ID: abf7d3c28c46
Revises: 131f7fe8d29a
Create Date: 2026-04-27 11:01:27.000021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abf7d3c28c46'
down_revision: Union[str, Sequence[str], None] = '131f7fe8d29a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'roles', 'users', ['owner_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_column('roles', 'owner_id')
    # ### end Alembic commands ###
