"""add relation to db project, task, team model

Revision ID: d042f09072c0
Revises: 8ee026ffd140
Create Date: 2026-04-26 10:33:21.178912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd042f09072c0'
down_revision: Union[str, Sequence[str], None] = '8ee026ffd140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('team_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_projects_team_id'), 'projects', ['team_id'], unique=False)
    op.create_foreign_key(None, 'projects', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.add_column('tasks', sa.Column('project_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_column('tasks', 'project_id')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_team_id'), table_name='projects')
    op.drop_column('projects', 'team_id')
    # ### end Alembic commands ###
